node {
        stage('Build') {
        	sh 'cd TestApp && mvn -B -DskipTests clean package'
        }
        stage('Test') {
        	sh 'cd TestApp && mvn test' 
        }
        stage('Deploy') {
        	sh 'rm -r /home/patrick/UniOsnabrueck/SeminarSoftwareEngineering/Git/ContinuousDeliverySample/TestApp/target/* && cp -r target/*  /home/patrick/UniOsnabrueck/SeminarSoftwareEngineering/Git/ContinuousDeliverySample/TestApp/target/.'
        }
}