node {
        stage('Build') {
        	sh 'cd TestApp'
            sh 'mvn -B -DskipTests clean package'
        }
        stage('Test') {
        	sh 'cd TestApp' 
            sh 'mvn test' 
        }
}