node {
        stage('Build') {
        	sh 'cd TestApp && mvn -B -DskipTests clean package'
        }
        stage('Test') {
        	sh 'cd TestApp && mvn test' 
        }
        stage('Execute') {
        	sh 'java -cp TestApp/target/TestApp-1.0-SNAPSHOT.jar com.swe.testapp.App'
        }
}        